version: '3.8'

services:

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: eventdb-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: eventdb
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - event-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: eventdb-redis
    restart: always
    ports:
      - "6380:6379"
    networks:
      - event-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Spring Boot App
  app:
    build: .
    container_name: event-reservation-app
    restart: always
    ports:
      - "8081:8081"
    environment:
      # Database
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/eventdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      # Redis
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      # JWT
      SECURITY_JWT_SECRET_KEY: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      SECURITY_JWT_EXPIRATION_TIME: 86400000
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - event-network

networks:
  event-network:
    driver: bridge

volumes:
  mysql-data: